apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - ns: prod
      - ns: staging
      - ns: qa
  template:
    metadata:
      name: '{{ns}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BillyGrande/gitops-cert-level-2-examples/
        targetRevision: HEAD
        path: ./environment-promotion/envs/{{ns}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
